[build]
  # Directory to change to before starting a build
  base = "frontend"

  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

  # Default build command
  command = "npm run build"

[[redirects]]
  # Redirect all routes to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
